collections:
  gnet_resources:
    output: true
    permalink: /game-networking/resources/:path

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "gnet_resources"
    values:
      layout: "gnet_resource"